services:
  postgres:
    container_name: Events
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: events-backend
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads  

volumes:
  pgdata:
