# This is a basic GitHub Actions workflow for a web application.
# It automatically runs whenever code is pushed to the 'main', 'front-end', or 'backend' branches,
# or when a pull request is created.
name: Event Planner CI

on:
  push:
    branches:
      - main
      - frontend
      - backend
  pull_request:
    branches:
      - main
      - frontend
      - backend

jobs:
  frontend:
    if: contains(github.ref, 'frontend') || github.ref == 'refs/heads/main'
    name: Frontend (Next.js)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Test frontend
        run: npm run test

  backend:
    if: contains(github.ref, 'backend') || github.ref == 'refs/heads/main'
    name: Backend (NestJS)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm ci

      - name: Generate Prisma Client (if applicable)
        run: npx prisma generate

      - name: Build backend
        run: npm run build

      - name: Test backend
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy frontend to S3
        run: |
          echo "Deploying frontend to S3..."
          aws s3 sync ./frontend/out s3://my-event-planner-bucket --delete

      - name: Deploy backend to EC2 or other service
        run: |
          echo "Deploying backend..."
          # Replace with your backend deployment logic

          echo "Deploying the application to S3..."
          # The 'build' directory is typically where the compiled code is located.
          aws s3 sync ./build s3://my-event-planner-bucket --delete
